language: python

matrix:
  include:
    python: 3.5.2
    sudo: true

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'create database questioner_db;' -U postgres
  - psql -c 'create database test_questioner;' -U postgres
 
script:
  - pytest --cov=app/
  
after_success:
  - coveralls

cache: pip