language: python

matrix:
  include:
    python: 3.5.2
    sudo: true

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'create database test_questioner;' -U postgres
  - export SECRET_KEY=b'\xb2\xa9J\xbec\x8e8d}\x16\xe8[\x9f\x10\xc9j\xaf7:\x955\xa8eT'
  - export TEST_DB_URL="dbname='test_questioner' user='postgres' password='' host='localhost'"
  - export FLASK_ENV="testing"

 
script:
  - pytest --cov=app/
  
after_success:
  - coveralls

cache: pip